# ─────────────────────────────────────────────────────────────────────────────
# Random suffix — 5-char lowercase alphanumeric, stable across applies
# Appended to every resource name to avoid collisions between deployments.
# ─────────────────────────────────────────────────────────────────────────────
resource "random_string" "suffix" {
  length  = 5
  upper   = false
  special = false
}

# ─────────────────────────────────────────────────────────────────────────────
# Availability Zones — resolved at plan time from the configured region
# ─────────────────────────────────────────────────────────────────────────────
data "aws_availability_zones" "available" {
  state = "available"
}

locals {
  suffix = random_string.suffix.result
  # Use the first N available AZs in the region, where N = number of public
  # subnet CIDRs supplied. This keeps AZ count in sync with the subnet lists.
  azs = slice(data.aws_availability_zones.available.names, 0, length(var.public_subnet_cidrs))
}

# ─────────────────────────────────────────────────────────────────────────────
# SSH Key Pair — generated by Terraform; private key written to ./ssh_key
# ─────────────────────────────────────────────────────────────────────────────
module "ssh_key" {
  source = "./modules/ssh_key"

  project_name = var.project_name
  environment  = var.environment
  suffix       = local.suffix
  tags         = var.tags
}

# ─────────────────────────────────────────────────────────────────────────────
# VPC + Internet Gateway
# ─────────────────────────────────────────────────────────────────────────────
module "vpc" {
  source = "./modules/vpc"

  project_name     = var.project_name
  environment      = var.environment
  suffix           = local.suffix
  vpc_cidr         = var.vpc_cidr
  enable_flow_logs = true
  tags             = var.tags
}

# ─────────────────────────────────────────────────────────────────────────────
# Subnets — 2 public + 4 private (2 per AZ)
# ─────────────────────────────────────────────────────────────────────────────
module "subnets" {
  source = "./modules/subnets"

  project_name         = var.project_name
  environment          = var.environment
  suffix               = local.suffix
  vpc_id               = module.vpc.vpc_id
  availability_zones   = local.azs
  public_subnet_cidrs  = var.public_subnet_cidrs
  private_subnet_cidrs = var.private_subnet_cidrs
  tags                 = var.tags
}

# ─────────────────────────────────────────────────────────────────────────────
# Security Groups — ALB + EC2
# ─────────────────────────────────────────────────────────────────────────────
module "security_groups" {
  source = "./modules/security_groups"

  project_name      = var.project_name
  environment       = var.environment
  suffix            = local.suffix
  vpc_id            = module.vpc.vpc_id
  ssh_allowed_cidrs = var.ssh_allowed_cidrs
  tags              = var.tags
}

# ─────────────────────────────────────────────────────────────────────────────
# Application Load Balancer
# ─────────────────────────────────────────────────────────────────────────────
module "alb" {
  source = "./modules/alb"

  project_name               = var.project_name
  environment                = var.environment
  suffix                     = local.suffix
  vpc_id                     = module.vpc.vpc_id
  public_subnet_ids          = module.subnets.public_subnet_ids
  alb_sg_id                  = module.security_groups.alb_sg_id
  enable_deletion_protection = var.enable_alb_deletion_protection
  tags                       = var.tags
}

# ─────────────────────────────────────────────────────────────────────────────
# GWLB Endpoints — one per private-gwlb subnet (one per AZ)
# Connects to an endpoint service running in a remote AWS account.
# IMPORTANT: Routes that target these endpoints (igw_to_gwlb, private_to_gwlb)
# require the remote service owner to ACCEPT the endpoints before apply
# succeeds. Apply in two phases if the service does not have auto-accept:
#   Phase 1: apply with create_routes = false (or comment out aws_route resources)
#   Phase 2: after acceptance, apply again to create the routes.
# ─────────────────────────────────────────────────────────────────────────────
module "gwlb_endpoints" {
  source = "./modules/gwlb_endpoints"

  project_name          = var.project_name
  environment           = var.environment
  suffix                = local.suffix
  vpc_id                = module.vpc.vpc_id
  subnet_az_map         = zipmap(local.azs, module.subnets.private_gwlb_subnet_ids)
  endpoint_service_name = var.gwlb_endpoint_service_name
  tags                  = var.tags
}

# ─────────────────────────────────────────────────────────────────────────────
# Routing — IGW RT, Public RT, App RTs, GWLB RT
# Declared after gwlb_endpoints because routes depend on endpoint IDs.
# ─────────────────────────────────────────────────────────────────────────────
module "routing" {
  source = "./modules/routing"

  project_name            = var.project_name
  environment             = var.environment
  suffix                  = local.suffix
  vpc_id                  = module.vpc.vpc_id
  igw_id                  = module.vpc.igw_id
  public_subnet_ids       = module.subnets.public_subnet_ids
  public_subnet_cidrs     = module.subnets.public_subnet_cidrs
  private_app_subnet_ids  = module.subnets.private_app_subnet_ids
  private_gwlb_subnet_ids = module.subnets.private_gwlb_subnet_ids
  gwlb_endpoint_ids       = [for az in local.azs : module.gwlb_endpoints.endpoint_ids[az]]
  tags                    = var.tags
}

# ─────────────────────────────────────────────────────────────────────────────
# Bastion Host — Ubuntu t3.micro in public-subnet-1; SSH via ./ssh_key
# NOTE: public subnet RT routes 0.0.0.0/0 → GWLB endpoint. The bastion's
# outbound traffic (including SSH responses) also traverses the GWLB. The
# bastion will not be reachable until the GWLB endpoints are accepted and
# routes are in place. Use the two-phase apply if endpoints require manual
# acceptance by the remote service owner.
# ─────────────────────────────────────────────────────────────────────────────
module "bastion" {
  source = "./modules/bastion"

  project_name      = var.project_name
  environment       = var.environment
  suffix            = local.suffix
  vpc_id            = module.vpc.vpc_id
  subnet_id         = module.subnets.public_subnet_ids[0]
  key_name          = module.ssh_key.key_name
  ssh_allowed_cidrs = var.bastion_ssh_allowed_cidrs
  tags              = var.tags
}

# ─────────────────────────────────────────────────────────────────────────────
# EC2 — 2 NGINX instances in private-app subnets (one per AZ)
# private_subnet_ids[0..1] are the app-tier subnets; [2..3] are for ZTG GWLB endpoints
# ─────────────────────────────────────────────────────────────────────────────
module "ec2" {
  source = "./modules/ec2"

  project_name       = var.project_name
  environment        = var.environment
  suffix             = local.suffix
  subnet_az_map      = zipmap(local.azs, module.subnets.private_app_subnet_ids)
  ec2_sg_id          = module.security_groups.ec2_sg_id
  target_group_arn   = module.alb.target_group_arn
  instance_type      = var.instance_type
  key_name           = module.ssh_key.key_name
  tags               = var.tags
}
